version: "2"

services:

  nginx:
    image: 'nginx:stable'
    networks:
      - services_network
    ports:
      - 80:80
    volumes:
      - sockets:/sockets/
      - ./nginx/default.dev.conf:/etc/nginx/nginx.conf
      - ./config/services.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookify_backend

  bookify_backend:
    image: 'bookify_backend:dev'
    command: uwsgi app.ini
    environment:
      - APP_CONFIG=development
      - ADMINS=a.verdier@outlook.fr
      - DATABASE_URI=sqlite:////database/app.db
      - PRIVATE_KEY=/keys/auth_privkey.pem
      - PUBLIC_KEY=/keys/auth_pubkey.pem
      - MAIL_SERVER=smtp
      - MAIL_PORT=25
      - LOG_PATH=/logs/bookify_backend.log
    volumes:
      - sockets:/sockets/
      - ./logs:/logs
      - ./keys:/keys/
      - ./config/app.ini:/bookify/app.ini
      - ./database:/database/
    networks:
      - services_network

  smtp:
    image: tophfr/mailcatcher
    ports:
      - 1080:80
    networks:
      - services_network

volumes:
  sockets:
    driver: local

networks:
  services_network:
    driver: bridge